config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  resources :posts

  devise_for :admins, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  devise_for :users, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
  # has_many_attached :images
  belongs_to :admin
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]

  def index
    @posts = Post.with_rich_text_content
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    @post.admin = current_admin
    if @post.save
      flash[:notice] = "投稿しました。"
      redirect_to @post
    else
      render "new", status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "投稿を更新しました。"
      redirect_to @post
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, status: :see_other
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, class: "bg-white py-5 rounded-md trix-content post-form" do |f| %>
  <div class="mb-3">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"  %>
  </div>
  <div class="mb-3">
    <%= f.label :content, "記事" %>
    <%= f.rich_text_area :content, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="mb-3">
    <%= f.submit @post.new_record? ? "投稿する" : "更新する", class: "font-semibold py-2 px-4 rounded text-white bg-sky-600 hover:bg-sky-500 cursor-pointer" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h1>投稿の編集</h1>
  <%= render "form" %>
  <%= link_to "投稿の削除", post_path(@post), class: "btn btn-red", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %>
</div>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<div class="mb-3 max-w-2xl text-left mx-auto">
  <% if admin_signed_in? %>
    <div class="my-3">
      <%= link_to "投稿の編集", edit_post_path, class: "btn btn-sky" %>
    </div>
  <% end %>
  <div class="my-8 text-3xl">
    <h1><%= @post.title %></h1>
  </div>
  <div class="mb-3 post-content">
    <%= @post.content %>
  </div>
  <% if admin_signed_in? %>
    <div class="my-3">
      <%= link_to "投稿の編集", edit_post_path, class: "btn btn-sky" %>
    </div>
  <% end %>
</div>